### ISSUE TITLE
Add option to include gun.path

### ISSUE THREAD

**Issue by sebastianmacias** [sjones6/vue-gun#2]
gun.path is [not included](http://gun.js.org/docs/path.html) by default.

When trying to use it, I'm getting errors like this:

```javascript
Uncaught TypeError: this.$gun.get(...).path is not a function
    at VueComponent.sendMsg (index.vue:82)
    at Proxy.boundFn (vue.runtime.esm.js:179)
    at click (index.vue?9cc7:55)
    at HTMLButtonElement.invoker (vue.runtime.esm.js:1817)
```

Thanks

**Comment by sjones6** [comment]
@sebastianmacias : Thanks for opening the issue.

This method was removed from gun core a few iterations back, and unfortunately, the docs haven't been updated to reflect that.

If you want the `gun.path` method, you can still include it like so (even in client-side code):

```javascript
import Gun from 'gun'
import 'node_modules/gun/lib/path.js'

// ... or 
const Gun = require('gun')
require('node_modules/gun/lib/path.js')
```

Does that help?

**Comment by sebastianmacias** [comment]
Thanks @sjones6, it worked

**Comment by sjones6** [comment]
Glad it worked it. Thanks!
