### ISSUE TITLE
A question about the Usability

### ISSUE THREAD

**Issue by zjyzh** [sjones6/vue-gun#4]
# It seems that this module hasn't been updated for two years, Is this still under support? If I use this module in my project, Can I get the latest version of GUN?
I would appreciate it if you can answer my question, thank you very much

**Comment by sjones6** [comment]
Unless there’s a compat change with this library and Gun, you should be able to use whatever version of Gun you want. Simply pass your gun instance into the constructor. 

The package declaration for the Gun dep declares “*”, so npm/yarn should pick up whatever version you already have installed on your project or the latest version.
