### ISSUE TITLE
A question about import Radix storage engine into the Project 

### ISSUE THREAD

**Issue by zjyzh** [sjones6/vue-gun#5]
I use vue-gun by initializing it in this way:
 ```import VueGun from 'vue-gun';
import 'gun/lib/rindexed';
import 'gun/lib/radix';
import 'gun/lib/radisk';
Vue.use(VueGun, {
  peers: ['.../gun', '  .../gun'],
  radisk: true,
  localStorage: false
});
``` 
 But after I Refresh my Browser, I couldn't get data from GUN, I want to ask is there any problem with my code when I'm using RED API ?

**Comment by zjyzh** [comment]
If I enable local Storage and push a file larger than 5Mb, My console will have the following tips: 
``` 
QuotaExceededError: Failed to execute 'setItem' on 'Storage': Setting the value of 'gun/' exceeded the quota. 
Consider using GUN's IndexedDB plugin for RAD for more storage space, https://gun.eco/docs/RAD#install
```

**Comment by sjones6** [comment]
I don’t think this a problem Vue-Gun but Gun itself. Suggest filing an issue there

**Comment by amark** [comment]
@sjones6 woah! you're alive! How are you doing? How's the family? What are you up to? :)

**Comment by sjones6** [comment]
Hey @amark , so I am :) doing pretty well—2 kids now and a pretty intense startup job, hasn’t left much time for OS last few years. Looks like things are still pretty active in the GUN world!
